if(typeof Object.create!=='function'){Object.create=function(obj){function F(){}
F.prototype=obj;return new F();};}
(function($,window,document,undefined){var Slider={init:function(options,elem){var self=this;$("body").removeClass("coda-slider-no-js");$('.coda-slider').prepend('<p class="loading">Loading...<br /><img src="./img/ajax-loader.gif" width="220" height="19" alt="loading..." /></p>');self.elem=elem;self.$elem=$(elem);self.sliderId='#'+(self.$elem).attr('id');self.options=$.extend({},$.fn.codaSlider.options,options);self.sliderId='#'+(self.$elem).attr('id');self.build();if(self.options.autoSlide){self.autoSlide();}
self.events();$("p.loading").remove();},build:function(){var self=this;if($(self.sliderId).parent().attr('class')!='coda-slider-wrapper'){$(self.sliderId).wrap('<div id="'+(self.$elem).attr('id')+'-wrapper" class="coda-slider-wrapper"></div>');}
self.panelClass=self.sliderId+' .'+$(self.sliderId+" > div").addClass('panel').attr('class');$(self.panelClass).wrapAll('<div class="panel-container"></div>');if($(self.panelClass).children().attr('class')!='panel-wrapper'){$(self.panelClass).wrapInner('<div class="panel-wrapper"></div>');}
self.panelContainer=($(self.panelClass).parent());self.currentTab=self.options.firstPanelToLoad-1;if(self.options.autoHeight){$(self.sliderId).css('height',$($(self.panelContainer).children()[self.currentTab]).height()+$(self.sliderId+'-wrapper .coda-nav-right').height());}
if(self.options.dynamicTabs){self.addNavigation();}
if(self.options.dynamicArrows){self.addArrows();}
self.totalSliderWidth=$(self.sliderId).outerWidth(true)+$($(self.sliderId).parent()).children('[class^=coda-nav-left]').outerWidth(true)+$($(self.sliderId).parent()).children('[class^=coda-nav-right]').outerWidth(true);$($(self.sliderId).parent()).css('width',self.totalSliderWidth);if(self.options.dynamicTabs){self.alignNavigation();}
if(self.options.continuous){$(self.panelContainer).prepend($(self.panelContainer).children().last().clone());$(self.panelContainer).append($(self.panelContainer).children().eq(1).clone());}
self.clickable=true;self.panelCount=$(self.panelClass).length;self.panelWidth=$(self.panelClass).outerWidth();self.totalWidth=self.panelCount*self.panelWidth;self.pSign='px';self.slideWidth=$(self.sliderId).width();$(self.panelContainer).css('margin-left',(-self.slideWidth*~~(self.options.continuous))+(-self.slideWidth*self.currentTab));self.setCurrent(self.currentTab);$(self.sliderId+' .panel-container').css('width',self.totalWidth);},addNavigation:function(){var self=this;var dynamicTabs='<div class="coda-nav"><ul></ul></div>';if(self.options.dynamicTabsPosition==='bottom'){$(self.sliderId).after(dynamicTabs);}
else{$(self.sliderId).before(dynamicTabs);}
$.each((self.$elem).find(self.options.panelTitleSelector),function(n){$($(self.sliderId).parent()).find('.coda-nav ul').append('<li class="tab'+(n+1)+'"><a href="#'+(n+1)+'" title="'+$(this).text()+'">'+$(this).text()+'</a></li>');});},alignNavigation:function(){var self=this;self.totalNavWidth=0;var arrow='';if(self.options.dynamicArrowsGraphical){arrow='-arrow';}
if(self.options.dynamicTabsAlign!='center'){$($(self.sliderId).parent()).find('.coda-nav ul').css('margin-'+self.options.dynamicTabsAlign,$($(self.sliderId).parent()).find('.coda-nav-'+self.options.dynamicTabsAlign+arrow).outerWidth(true)+parseInt($(self.sliderId).css('margin-'+self.options.dynamicTabsAlign),10));$($(self.sliderId).parent()).find('.coda-nav ul').css('float',self.options.dynamicTabsAlign);}
else{$($(self.sliderId).parent()).find('.coda-nav li a').each(function(){self.totalNavWidth+=$(this).outerWidth(true);});if($.browser.msie){self.totalNavWidth=self.totalNavWidth+(5);}
$($(self.sliderId).parent()).find('.coda-nav ul').css('width',self.totalNavWidth+1);}},addArrows:function(){var self=this;$(self.sliderId).parent().addClass("arrows");if(self.options.dynamicArrowsGraphical){$(self.sliderId).before('<div class="coda-nav-left-arrow" data-dir="prev" title="Slide left"><a href="#"></a></div>');$(self.sliderId).after('<div class="coda-nav-right-arrow" data-dir="next" title="Slide right"><a href="#"></a></div>');}
else{$(self.sliderId).before('<div class="coda-nav-left" data-dir="prev" title="Slide left"><a href="#">'+self.options.dynamicArrowLeftText+'</a></div>');$(self.sliderId).after('<div class="coda-nav-right" data-dir="next" title="Slide right"><a href="#">'+self.options.dynamicArrowRightText+'</a></div>');}},events:function(){var self=this;$($(self.sliderId).parent()).find('[class^=coda-nav-]').on('click',function(e){if(!self.clickable&&self.options.continuous){return false;}
self.setCurrent($(this).attr('class').split('-')[2]);if(self.options.continuous){self.clickable=false;}
return false;});$($(self.sliderId).parent()).find('[class^=coda-nav] li').on('click',function(e){if(!self.clickable&&self.options.continuous){return false;}
self.setCurrent(parseInt($(this).attr('class').split('tab')[1],10)-1);if(self.options.continuous){self.clickable=false;}
return false;});$('[data-ref*='+(self.sliderId).split('#')[1]+']').on('click',function(e){if(!self.clickable&&self.options.continuous){return false;}
if(self.options.autoSlideControls){if($(this).attr('name')==='stop'){$(this).html(self.options.autoSlideStartText).attr('name','start');clearTimeout(self.autoslideTimeout);return false;}
if($(this).attr('name')==='start'){$(this).html(self.options.autoSlideStopText).attr('name','stop');self.setCurrent(self.currentTab+1);self.autoSlide();return false;}}
self.setCurrent(parseInt($(this).attr('href').split('#')[1]-1,10));if(self.options.continuous){self.clickable=false;}
if(self.options.autoSlideStopWhenClicked){clearTimeout(self.autoslideTimeout);}
return false;});$($(self.sliderId).parent()).find('*').on('click',function(e){if(self.options.autoSlideControls&&self.options.autoSlideStopWhenClicked){$('body').find('[data-ref*='+(self.sliderId).split('#')[1]+'][name=stop]').html(self.options.autoSlideStartText);clearTimeout(self.autoslideTimeout);}
if(!self.clickable&&self.options.continuous){if(self.options.autoSlideStopWhenClicked){clearTimeout(self.autoslideTimeout);}
return false;}
if(self.options.autoSlide){if(self.options.autoSlideStopWhenClicked){clearTimeout(self.autoslideTimeout);}
else{self.autoSlide(clearTimeout(self.autoslideTimeout));self.clickable=true;}}
if(self.options.continuous){clearTimeout(self.continuousTimeout);}});},setCurrent:function(direction){var self=this;if(self.clickable){if(typeof direction=='number'){self.currentTab=direction;}
else{self.currentTab+=(~~(direction==='right')||-1);if(!self.options.continuous){self.currentTab=(self.currentTab<0)?this.panelCount-1:(self.currentTab%this.panelCount);}}
if(self.options.continuous){self.panelHeightCount=self.currentTab+1;if(self.currentTab===self.panelCount-2){self.setTab=0;}
else if(self.currentTab===-1){self.setTab=self.panelCount-3;}
else{self.setTab=self.currentTab;}}
else{self.panelHeightCount=self.currentTab;self.setTab=self.currentTab;}
$($(self.sliderId).parent()).find('.tab'+(self.setTab+1)+' a:first').addClass('current').parent().siblings().children().removeClass('current');this.transition();}},transition:function(){var self=this;if(self.options.autoHeight){$(self.panelContainer).parent().animate({'height':$($(self.panelContainer).children()[self.panelHeightCount]).height()},{easing:self.options.autoHeightEaseFunction,duration:self.options.autoHeightEaseDuration,queue:false});}
if(self.options.continuous){self.marginLeft=-(self.currentTab*self.slideWidth)-self.slideWidth;}
else{self.marginLeft=-(self.currentTab*self.slideWidth);}
(self.panelContainer).animate({'margin-left':self.marginLeft+self.pSign},{easing:self.options.slideEaseFunction,duration:self.options.slideEaseDuration,queue:false,complete:self.continuousSlide(self.options.slideEaseDuration+50)});},autoSlide:function(){var self=this;if(self.options.autoSlideInterval<self.options.slideEaseDuration){self.options.autoSlideInterval=(self.options.slideEaseDuration>self.options.autoHeightEaseDuration)?self.options.slideEaseDuration:self.options.autoHeightEaseDuration;}
if(self.options.continuous){self.clickable=false;}
self.autoslideTimeout=setTimeout(function(){self.setCurrent(self.options.autoSliderDirection);self.autoSlide();},self.options.autoSlideInterval);},continuousSlide:function(delay){var self=this;if(self.options.continuous){self.continuousTimeout=setTimeout(function(){if(self.currentTab===self.panelCount-2){$(self.panelContainer).css('margin-left',-self.slideWidth+self.pSign);self.currentTab=0;}
else if(self.currentTab===-1){$(self.panelContainer).css('margin-left',-(((self.slideWidth*self.panelCount)-(self.slideWidth*2)))+self.pSign);self.currentTab=(self.panelCount-3);}
self.clickable=true;},delay);}
else{self.clickable=true;}}};$.fn.codaSlider=function(options){return this.each(function(){var slider=Object.create(Slider);slider.init(options,this);});};$.fn.codaSlider.options={autoHeight:true,autoHeightEaseDuration:1500,autoHeightEaseFunction:"easeInOutExpo",autoSlide:false,autoSliderDirection:'right',autoSlideInterval:7000,autoSlideControls:false,autoSlideStartText:'Start',autoSlideStopText:'Stop',autoSlideStopWhenClicked:true,continuous:true,crossLinking:true,dynamicArrows:true,dynamicArrowsGraphical:false,dynamicArrowLeftText:"&#171; left",dynamicArrowRightText:"right &#187;",dynamicTabs:true,dynamicTabsAlign:"center",dynamicTabsPosition:"top",externalTriggerSelector:"a.xtrig",firstPanelToLoad:1,panelTitleSelector:"h2.title",slideEaseDuration:1500,slideEaseFunction:"easeInOutExpo"};})(jQuery,window,document);